version: '3'
services:
  strapi:
    volumes:
      - ./app:/srv/app
    ports:
      - '1337:1337'
#    user: '1000'
    build:
      context: .
      args:
        BASE_VERSION: 16
        STRAPI_VERSION: 3.6.3
        USER_NAME: 'user'
